


insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '10102', 'UNIVERSITY MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '10131', 'OAK TREE MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '10707', 'TUSTIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '34439', 'WANTAGH MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '34521', 'MAZDA OF NORTH MIAMI'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '34541', 'MAZDA SOUTH'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '50210', 'OCEAN MAZDA'				, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '51617', 'CULVER CITY MAZDA'		    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61566', 'GALPIN MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '10803', 'CLASSIC MAZDA'			    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '10823', 'CAPITOL MAZDA'			    , 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '34575', 'CARDINALEWAY MAZDA VEGAS'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61534', 'SPORT MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61593', 'MAZDA OF DELRAY BEACH'	    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61622', 'WAYNE MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61623', 'GUNTHER MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61624', 'MAZDA OF LODI'			    , 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '60135', 'CORY FAIRBANKS MAZDA'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61420', 'JEFF HAAS MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61429', 'BOB BAKER MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61449', 'MAZDA OF SOUTH CHARLOTTE'	, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61540', 'MAZDA OF EVERETT'			, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61590', 'QUIRK MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61610', 'WALSER BURNSVILLE MAZDA'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61614', 'NORTH PARK MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61635', 'LUTHER BROOKDALE MAZDA'	, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '60181', 'DUBLIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61471', 'ROGER MAZDA GEORGETOWN'	, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61611', 'HAMILTON MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61613', 'NORTH PENN MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61626', 'MORRIES MINNETONKA MAZDA'	, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61629', 'MAZDA OF WEST CHESTER'	    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61637', 'PUTNAM MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '60170', 'SMITH HAVEN MAZDA'		    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '60172', 'RILEY MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '60188', 'PALISADES MAZDA'			, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61432', 'CLASSIC MAZDA'			    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61504', 'WERNER MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61542', 'MAZDA OF WEST RIDGE'		, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61561', 'MORRIES INVER GROVE MAZDA' , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '61628', 'COLONIAL MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '34638', 'PUGI MAZDA'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (01, 2021, 20, '70150', 'FREEWAY MAZDA'			    , 'A', 'GU', '02', '02')

insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '10102', 'UNIVERSITY MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '10131', 'OAK TREE MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '10707', 'TUSTIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '34439', 'WANTAGH MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '34521', 'MAZDA OF NORTH MIAMI'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '34541', 'MAZDA SOUTH'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '50210', 'OCEAN MAZDA'				, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '51617', 'CULVER CITY MAZDA'		    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61566', 'GALPIN MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '10803', 'CLASSIC MAZDA'			    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '10823', 'CAPITOL MAZDA'			    , 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '34575', 'CARDINALEWAY MAZDA VEGAS'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61534', 'SPORT MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61593', 'MAZDA OF DELRAY BEACH'	    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61622', 'WAYNE MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61623', 'GUNTHER MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61624', 'MAZDA OF LODI'			    , 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '60135', 'CORY FAIRBANKS MAZDA'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61420', 'JEFF HAAS MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61429', 'BOB BAKER MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61449', 'MAZDA OF SOUTH CHARLOTTE'	, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61540', 'MAZDA OF EVERETT'			, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61590', 'QUIRK MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61610', 'WALSER BURNSVILLE MAZDA'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61614', 'NORTH PARK MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61635', 'LUTHER BROOKDALE MAZDA'	, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '60181', 'DUBLIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61471', 'ROGER MAZDA GEORGETOWN'	, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61611', 'HAMILTON MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61613', 'NORTH PENN MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61626', 'MORRIES MINNETONKA MAZDA'	, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61629', 'MAZDA OF WEST CHESTER'	    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61637', 'PUTNAM MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '60170', 'SMITH HAVEN MAZDA'		    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '60172', 'RILEY MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '60188', 'PALISADES MAZDA'			, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61432', 'CLASSIC MAZDA'			    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61504', 'WERNER MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61542', 'MAZDA OF WEST RIDGE'		, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61561', 'MORRIES INVER GROVE MAZDA' , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '61628', 'COLONIAL MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '34638', 'PUGI MAZDA'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (02, 2021, 10, '70150', 'FREEWAY MAZDA'			    , 'A', 'GU', '02', '02')

insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '10102', 'UNIVERSITY MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '10131', 'OAK TREE MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '10707', 'TUSTIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '34439', 'WANTAGH MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '34521', 'MAZDA OF NORTH MIAMI'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '34541', 'MAZDA SOUTH'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '50210', 'OCEAN MAZDA'				, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '51617', 'CULVER CITY MAZDA'		    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61566', 'GALPIN MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '10803', 'CLASSIC MAZDA'			    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '10823', 'CAPITOL MAZDA'			    , 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '34575', 'CARDINALEWAY MAZDA VEGAS'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61534', 'SPORT MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61593', 'MAZDA OF DELRAY BEACH'	    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61622', 'WAYNE MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61623', 'GUNTHER MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61624', 'MAZDA OF LODI'			    , 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '60135', 'CORY FAIRBANKS MAZDA'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61420', 'JEFF HAAS MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61429', 'BOB BAKER MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61449', 'MAZDA OF SOUTH CHARLOTTE'	, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61540', 'MAZDA OF EVERETT'			, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61590', 'QUIRK MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61610', 'WALSER BURNSVILLE MAZDA'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61614', 'NORTH PARK MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61635', 'LUTHER BROOKDALE MAZDA'	, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '60181', 'DUBLIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61471', 'ROGER MAZDA GEORGETOWN'	, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61611', 'HAMILTON MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61613', 'NORTH PENN MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61626', 'MORRIES MINNETONKA MAZDA'	, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61629', 'MAZDA OF WEST CHESTER'	    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61637', 'PUTNAM MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '60170', 'SMITH HAVEN MAZDA'		    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '60172', 'RILEY MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '60188', 'PALISADES MAZDA'			, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61432', 'CLASSIC MAZDA'			    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61504', 'WERNER MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61542', 'MAZDA OF WEST RIDGE'		, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61561', 'MORRIES INVER GROVE MAZDA' , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '61628', 'COLONIAL MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '34638', 'PUGI MAZDA'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (03, 2021, 16, '70150', 'FREEWAY MAZDA'			    , 'A', 'GU', '02', '02')

insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '10102', 'UNIVERSITY MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '10131', 'OAK TREE MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '10707', 'TUSTIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '34439', 'WANTAGH MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '34521', 'MAZDA OF NORTH MIAMI'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '34541', 'MAZDA SOUTH'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '50210', 'OCEAN MAZDA'				, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '51617', 'CULVER CITY MAZDA'		    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61566', 'GALPIN MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '10803', 'CLASSIC MAZDA'			    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '10823', 'CAPITOL MAZDA'			    , 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '34575', 'CARDINALEWAY MAZDA VEGAS'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61534', 'SPORT MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61593', 'MAZDA OF DELRAY BEACH'	    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61622', 'WAYNE MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61623', 'GUNTHER MAZDA'			    , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61624', 'MAZDA OF LODI'			    , 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '60135', 'CORY FAIRBANKS MAZDA'		, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61420', 'JEFF HAAS MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61429', 'BOB BAKER MAZDA'			, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61449', 'MAZDA OF SOUTH CHARLOTTE'	, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61540', 'MAZDA OF EVERETT'			, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61590', 'QUIRK MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61610', 'WALSER BURNSVILLE MAZDA'	, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61614', 'NORTH PARK MAZDA'			, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61635', 'LUTHER BROOKDALE MAZDA'	, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '60181', 'DUBLIN MAZDA'				, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61471', 'ROGER MAZDA GEORGETOWN'	, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61611', 'HAMILTON MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61613', 'NORTH PENN MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61626', 'MORRIES MINNETONKA MAZDA'	, 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61629', 'MAZDA OF WEST CHESTER'	    , 'A', 'GU', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61637', 'PUTNAM MAZDA'				, 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '60170', 'SMITH HAVEN MAZDA'		    , 'A', 'MW', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '60172', 'RILEY MAZDA'				, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '60188', 'PALISADES MAZDA'			, 'A', 'MW', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61432', 'CLASSIC MAZDA'			    , 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61504', 'WERNER MAZDA'				, 'A', 'NE', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61542', 'MAZDA OF WEST RIDGE'		, 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61561', 'MORRIES INVER GROVE MAZDA' , 'A', 'NE', '02', '02')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '61628', 'COLONIAL MAZDA'			, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '34638', 'PUGI MAZDA'				, 'A', 'GU', '01', '01')
insert into RetailSales(month, year, qty, dealer_code, dealer_name, status, region, zone_details, district) values (04, 2021, 25, '70150', 'FREEWAY MAZDA'			    , 'A', 'GU', '02', '02')



